# Generated by Django 3.0.1 on 2020-05-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='location',
            field=models.CharField(default='', max_length=60),
        ),
    ]
