# Generated by Django 3.0.8 on 2020-11-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_missingvehicle_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='field_name',
            new_name='Time',
        ),
    ]
