# Generated by Django 3.0.8 on 2020-11-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20201126_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
