# Generated by Django 3.0.8 on 2020-11-26 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20201126_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 14, 46, 42, 53557, tzinfo=utc)),
        ),
    ]
