# Generated by Django 3.0.8 on 2020-11-26 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20201126_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Time',
            field=models.CharField(default=datetime.datetime(2020, 11, 26, 14, 53, 33, 567622, tzinfo=utc), max_length=60),
        ),
    ]
