# Generated by Django 3.0.8 on 2020-11-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20201126_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
