# Generated by Django 3.1.1 on 2021-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20201126_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='lat',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lon',
            field=models.CharField(default='', max_length=60),
        ),
    ]
