# Generated by Django 3.0.8 on 2021-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20210227_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingvehicle',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='missingvehicle',
            name='email',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='missingvehicle',
            name='licensenumber',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='missingvehicle',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
