# Generated by Django 3.0.8 on 2021-03-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20210306_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissingVehicle',
        ),
    ]
