# Generated by Django 3.0.8 on 2021-03-05 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingVehicle',
            fields=[
                ('missingVehicle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('licensenumber', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=12)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
