# Generated by Django 3.0.8 on 2021-03-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingvehicle',
            old_name='message',
            new_name='mes',
        ),
        migrations.AlterModelTable(
            name='missingvehicle',
            table='missingvehicle',
        ),
    ]
